### ISSUE TITLE
pwgan paddle2onnx

### ISSUE THREAD

**Issue by yt605155624** [RapidAI/RapidTTS2#2]
你好，我是 paddlespeech TTS 的研发，我发现你跑通了 pwgan 的 paddle2onnx，但是我自己在跑的时候会报错如下
![image](https://user-images.githubusercontent.com/24568452/162404423-0eaf6cea-84ec-4706-9112-d0d1c942a8df.png)
请问你是用哪个版本的 paddle2onnx 跑通的？

已解决

用如下命令会报错
```shell
paddle2onnx --model_dir inference  --model_filename pwgan_csmsc.pdmodel --params_filename pwgan_csmsc.pdiparams --save_file pwgan_csmsc.onnx
```
加上 --opset_version 11 就好了
```shell
paddle2onnx --model_dir inference  --model_filename pwgan_csmsc.pdmodel --params_filename pwgan_csmsc.pdiparams --save_file pwgan_csmsc.onnx --opset_version 11
```

**Comment by SWHL** [comment]
- 可以解决一下[Paddle2onnx转换acoustic模型到onnx 报错不支持算子](https://github.com/RapidAI/RapidTTS2/wiki/Paddle%E6%A8%A1%E5%9E%8B%E5%B0%9D%E8%AF%95%E8%BD%AC%E6%8D%A2#2022-04-06-paddle2onnx%E8%BD%AC%E6%8D%A2acoustic%E6%A8%A1%E5%9E%8B%E5%88%B0onnx)问题吗？
- 感谢

**Comment by yt605155624** [comment]
fastspeech2 模型现在可以 paddle2onnx 了，参考 https://github.com/PaddlePaddle/PaddleSpeech/blob/9fd495b7200d22c0e789d57e9df6a125d4443c59/examples/csmsc/tts3/run.sh#L46
speedyspeech 现在用 paddle2onnx 0.9.4 (需要加  --enable_dev_version True ) 不会少算子了，但是会报错如下：
![ccf294ac9d5abbb9065df374d0fc7182](https://user-images.githubusercontent.com/24568452/162425175-5b529a97-1b10-4a24-8bf4-8055f6e56ba2.png)
需要改变模型维度后重新训练并导出，正在做了 https://github.com/PaddlePaddle/PaddleSpeech/issues/1679

**Comment by SWHL** [comment]
- 感谢感谢，我去试试去
